chore: add make go-tidy and action for check modules is tidy

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,6 +23,32 @@ jobs:
         with:
           version: v1.46
 
+  tidy:
+    name: Go Tidy
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: "1.18"
+
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Tidy
+        run: make go-tidy
+
+      - name: Check Git Status
+        run: |
+          GIT_STATUS=$(git status --porcelain)
+          if [[ $GIT_STATUS ]]; then
+            echo $GIT_STATUS
+            echo "Git status is not clean, aborting"            
+            exit 1
+          else
+            echo "No changes after tidy, continuing"
+          fi
+
   test:
     name: Test
     runs-on: ubuntu-latest
