feat(tgb/session): session manager, store, filter (#93)
* feat(tg): add `Chat()` and `Msg()` methods to `Update`

* feat(tgb): middleware is interface now

* feat(session): prototype

* feat(tgb): rewrite Router for filter works like middleware

* feat(session): add BoltDB session store

* feat(session/bolt): finish store

* feat(session): add Reset method and delete session if it's initial

* chore: add go.work* to .gitignore

* feat(examples): add session filter

* fix(tgb): errFilterNoAllow text

* fix(tgb): error handler

* tests(tgb/session): add `MemoryStore` tests

* tests(tgb/session): increase coverage

* tests(tgb/session): cover Manager.Filter

* tests(tg): increase `Update` coverage

* fix(tgb/router): update only handler is not called

* docs(tgb/session/sessionbolt): package summary

* chore: tidy sessionbolt

* feat(tgb/session): add sessionsql store

* ci: add e2e tests

* ci: fix escape in health cmd

* ci: run only e2e tests

* ci: fix

* ci: fix

* ci: use localhost

* chore: remove db file

* ci: add logs

* ci: run e2e tests only if changed

* ci: run e2e tests only if changed

* feat(session/sessionsql): godoc

* docs(session): godoc

* docs(session): godoc

* docs(session): examples

* chore(tgb/session/sessionsql): remove `lib/pq` dep as uneed

* chore(tgb/session/sessionsql/e2e): go mod tidy

* chore: add make go-tidy and action for check modules is tidy

* ci: add new modules to dependabot

* ci: add sessionredis

* tests(tgb/session/sessionredis): e2e tags

* chore: go mod tidy

* ci: workspace init changes

* docs: sessionredis godoc

* docs: sessions in readme

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,6 +23,32 @@ jobs:
         with:
           version: v1.46
 
+  tidy:
+    name: Go Tidy
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: "1.18"
+
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Tidy
+        run: make go-tidy
+
+      - name: Check Git Status
+        run: |
+          GIT_STATUS=$(git status --porcelain)
+          if [[ $GIT_STATUS ]]; then
+            echo $GIT_STATUS
+            echo "Git status is not clean, aborting"            
+            exit 1
+          else
+            echo "No changes after tidy, continuing"
+          fi
+
   test:
     name: Test
     runs-on: ubuntu-latest
@@ -42,3 +68,91 @@ jobs:
         uses: codecov/codecov-action@v3
         with:
           token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
+
+  test-e2e:
+    name: Test Integration
+    runs-on: ubuntu-latest  # Service containers to run with `container-job`
+    services:
+      postgres:
+        image: postgres:14.4-alpine
+        env:
+          POSTGRES_USER: go-tg
+          POSTGRES_PASSWORD: go-tg
+          POSTGRES_DB: go-tg
+        options: >-
+          --health-cmd pg_isready
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
+        ports:
+          - 5432:5432
+      mysql:
+        image: mysql:8.0.30
+        env:
+          MYSQL_ROOT_PASSWORD: go-tg
+        options: 
+          --health-cmd "mysqladmin ping --password=go-tg --host localhost --user root"
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
+        ports:
+          - 3306:3306
+      
+      redis-v7:
+        image: redis:7-alpine
+
+        options: >-
+          --health-cmd "redis-cli ping"
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
+
+        ports:
+          - 63797:6379
+
+      redis-v6:
+        image: redis:7-alpine
+
+        options: >-
+          --health-cmd "redis-cli ping"
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
+
+        ports:
+          - 63796:6379
+
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - uses: dorny/paths-filter@v2
+        id: changes
+        with:
+          filters: |
+            e2e:
+              - 'tgb/session/sessionsql/**'
+              - 'tgb/session/sessionredis/**'
+
+      - name: Install Go
+        uses: actions/setup-go@v3
+        if: steps.changes.outputs.e2e == 'true'
+        with:
+          go-version: "1.18"
+
+
+      - name: Go Work 
+        if: steps.changes.outputs.e2e == 'true'
+        run: |
+          go work init . ./tgb/session/sessionbolt ./tgb/session/sessionredis ./tgb/session/sessionsql ./tgb/session/sessionsql/e2e ./tgb/session/sessionredis/e2e
+
+      - name: Test
+        if: steps.changes.outputs.e2e == 'true'
+        env:
+          POSTGRES_DSN: postgres://go-tg:go-tg@localhost:5432/go-tg?sslmode=disable
+          MYSQL_DSN: root:go-tg@tcp(localhost:3306)/mysql
+          REDIS_V7_DSN: redis://localhost:63797
+          REDIS_V6_DSN: redis://localhost:63796
+
+        run: go test -timeout 30s -v -race -tags e2e ./tgb/session/sessionsql/e2e
